/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Stitch design system — Studio Botema ERP
        'primary':                    '#aac7ff',
        'primary-container':          '#3e90ff',
        'on-primary':                 '#003064',
        'on-primary-container':       '#002957',
        'primary-fixed':              '#d6e3ff',
        'primary-fixed-dim':          '#aac7ff',
        'on-primary-fixed':           '#001b3e',
        'on-primary-fixed-variant':   '#00468d',
        'secondary':                  '#c6c5cf',
        'secondary-container':        '#4a4b53',
        'on-secondary':               '#2f3038',
        'on-secondary-container':     '#bcbbc5',
        'secondary-fixed':            '#e3e1ec',
        'secondary-fixed-dim':        '#c6c5cf',
        'on-secondary-fixed':         '#1a1b22',
        'on-secondary-fixed-variant': '#46464e',
        'tertiary':                   '#c7c5d0',
        'tertiary-container':         '#90909a',
        'on-tertiary':                '#2f3038',
        'on-tertiary-container':      '#292931',
        'tertiary-fixed':             '#e3e1ec',
        'tertiary-fixed-dim':         '#c7c5d0',
        'on-tertiary-fixed':          '#1a1b23',
        'on-tertiary-fixed-variant':  '#46464f',
        'error':                      '#ffb4ab',
        'error-container':            '#93000a',
        'on-error':                   '#690005',
        'on-error-container':         '#ffdad6',
        'warning':                    '#ffb800',
        'warning-container':          '#7a5500',
        'surface':                    '#09090b',
        'surface-dim':                '#06060a',
        'surface-bright':             '#2a2a2e',
        'surface-container-lowest':   '#050507',
        'surface-container-low':      '#111113',
        'surface-container':          '#161618',
        'surface-container-high':     '#1d1d1f',
        'surface-container-highest':  '#252528',
        'surface-variant':            '#252528',
        'surface-tint':               '#aac7ff',
        'on-surface':                 '#e8e4e8',
        'on-surface-variant':         '#b8bfcf',
        'background':                 '#09090b',
        'on-background':              '#e8e4e8',
        'outline':                    '#8b91a0',
        'outline-variant':            '#414754',
        'inverse-surface':            '#e5e1e4',
        'inverse-on-surface':         '#313032',
        'inverse-primary':            '#005db8',
      },
      borderRadius: {
        DEFAULT: '12px',
        sm:      '8px',
        md:      '12px',
        lg:      '14px',
        xl:      '16px',
        '2xl':   '20px',
        full:    '9999px',
      },
      spacing: {
        unit:                '4px',
        gutter:              '24px',
        'container-padding': '40px',
        'section-gap':       '64px',
        'element-gap':       '16px',
      },
      fontFamily: {
        'display':    ['"Cormorant Garamond"', 'Georgia', 'serif'],
        'headline':   ['"Playfair Display"', 'serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'data-mono':  ['Inter', 'sans-serif'],
        'body-md':    ['Inter', 'sans-serif'],
        'body-sm':    ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-caps':  ['11px', { lineHeight: '1.0', letterSpacing: '0.1em',  fontWeight: '600' }],
        'data-mono':   ['14px', { lineHeight: '1.0', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-md':     ['15px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm':     ['13px', { lineHeight: '1.4', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-lg':     ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-xl':  ['72px', { lineHeight: '0.95', letterSpacing: '-0.03em', fontWeight: '600' }],
        'display-lg':  ['56px', { lineHeight: '1.0',  letterSpacing: '-0.03em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
